FROM debian:latest
LABEL maintainer Leandro Moreira <leandro@leandromoreirati.com.br>

ARG  DEBIAN_VERSION=stretch
ARG  KEY=ABF5BD827BD9BF62

COPY configs/   /tmp/configs/

WORKDIR /srv/www/html/public_html

RUN dpkg -i /tmp/configs/zabbix-release_3.4-1+stretch_all.deb && \
    cat /usr/share/doc/apt/examples/sources.list > /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get dist-upgrade -y && \
    #apt-get install --no-install-recommends nginx php7.0-fpm php7.0-curl php7.0-gd php7.0-mysql php7.0-cli php7.0-imap php7.0-ldap php7.0-apcu php7.0-xmlrpc php7.0-mbstring php7.0-xml php-cas -y && \
    apt-get install --no-install-recommends ca-certificates apache2 libapache2-mod-php7.0 php7.0-cli php7.0 php7.0-gd php7.0-imap php7.0-ldap php7.0-mysql php7.0-soap php7.0-xmlrpc zip unzip bzip2 unrar-free php7.0-snmp php7.0-curl php7.0-json php-memcached php7.0-dev php7.0-mbstring php-apcu-bc php-casphp-cas php7.0-xm curl wget cron -y && \
    a2enmod xml2enc && \
    mv -v /tmp/configs/setup.sh /usr/bin/ && \
    mv -v /tmp/configs/site.conf /etc/nginx/sites-available/ && \
    mv -v /tmp/configs/www.conf /etc/php/7.0/fpm/pool.d/ && \
    mv -v /tmp/configs/php.ini /etc/php/7.0/fpm/ && \
    #mkdir -p /srv/www/html/public_html && \
    mkdir -p /run/php && \
    tar xvf /tmp/configs/glpi-9.3.1.tgz -C /srv/www/html/public_html && \
    #tar xvf /tmp/configs/fusioninventory-9.3.1.1.tar -C /srv/www/html/public_html/glpi/plugins && \
    #mv -v /tmp/configs/config_db.php /srv/www/html/public_html/glpi/config/ && \
    chown -R www-data:www-data /srv/www/html/public_html/glpi/ && \
    chmod -R 755 /srv/www/html/public_html/glpi && \
    chmod -R 777 /srv/www/html/public_html/glpi/plugins && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    apt-get purge -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /etc/nginx/sites-enabled/* && \
    rm -rf /tmp/* 
 
EXPOSE 80 443

#USER www-data

#ENTRYPOINT ["/usr/sbin/nginx"]

#CMD ["-g","daemon off;"]
