version: "3.7"
services:

# GLPI
  glpi-apache:
    image: leandromoreirajfa/glpi-apache:1.5
    command: setup.sh
    env_file:
      - glpi.config
    hostname: glpi-apache
    volumes:
      - www:/srv/www/html/public_html/glpi
      - $PWD/configs/ssl/fullchain1.pem:/etc/apache2/ssl/fullchain1.pem
      - $PWD/configs/ssl/privkey1.pem:/etc/apache2/ssl/privkey1.pem
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    deploy:
      #placement:
       # constraints: [node.role == manager]
      resources:
        limits:
          memory: 2048M
          cpus: '0.1'
        reservations:
          cpus: '0.5'
          memory: 1024M  
      restart_policy:
        condition: on-failure   
      #replicas: 3
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "3"
    networks:
      - backend

# VOLUMES
volumes:
  www:
 
# REDE
networks:
  backend:
    driver: overlay

  frontend:
    driver: overlay
